
num_graphs: 10               # Number of Bayesian networks to generate
max_depth: 10                # Maximum depth of any graph
min_children: 1              # Minimum number of children per node
max_children: 10              # Maximum number of children per node
output_dir : "./generated_graphs2"