
num_graphs: 1                # Number of Bayesian networks to generate
max_depth: 4                # Maximum depth of any graph
min_children: 1              # Minimum number of children per node
max_children: 4              # Maximum number of children per node
output_dir : "./generated_graphs"