_wandb:
    value:
        cli_version: 0.21.0
        e:
            zyborx6g3670z5ow45frvnt1gaofvlsk:
                args:
                    - --batch_size=32
                    - --dropout=0.3
                    - --hidden_dim=64
                    - --learning_rate=0.005
                codePath: train_graphsage.py
                codePathLocal: train_graphsage.py
                cpu_count: 10
                cpu_count_logical: 12
                disk:
                    /:
                        total: "248077348864"
                        used: "181918928896"
                email: st184833@stud.uni-stuttgart.de
                executable: C:\Users\simmi\thesis_python\BN_generator\venv\Scripts\python.exe
                git:
                    commit: b60c9b07f3e30f1c9a374b599dc2f98674b6383b
                    remote: https://github.com/simran610/gnn-graph-bayes.git
                host: LAPTOP-7JHOR56V
                memory:
                    total: "16832086016"
                os: Windows-10-10.0.26100-SP0
                program: C:\Users\simmi\thesis_python\BN_generator\train_graphsage.py
                python: CPython 3.10.8
                root: C:\Users\simmi\thesis_python\BN_generator
                startedAt: "2025-07-16T19:50:39.278686Z"
                writerId: zyborx6g3670z5ow45frvnt1gaofvlsk
        m: []
        python_version: 3.10.8
        t:
            "1":
                - 1
                - 77
            "2":
                - 1
                - 77
            "3":
                - 2
                - 16
            "4": 3.10.8
            "5": 0.21.0
            "8":
                - 3
            "12": 0.21.0
            "13": windows-amd64
batch_size:
    value: 32
dropout:
    value: 0.5
epochs:
    value: 100
hidden_channels:
    value: 32
lr:
    value: 0.001
patience:
    value: 5
weight_decay:
    value: 0.0005
